version: '3.3'

services:
  db:
    image: postgres
    restart: always
    env_file:
      - .env
    ports:
        - "8032:5432"
    volumes:
        - ./pgdata:/var/lib/postgresql/data/pgdata
        - ./sql/1_game_schema.sql:/docker-entrypoint-initdb.d/1_game_schema.sql
        - ./sql/2_game_insert_data.sql:/docker-entrypoint-initdb.d/2_game_insert_data.sql

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  rest_api_server:
    build: .
    restart: always
    ports:
        - "49160:8880"
    env_file:
      - .env
